spring:
  datasourse:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///edu_ad?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
